name = "hotwheels-collection"
compatibility_date = "2024-02-20"

[[d1_databases]]
binding = "DB"
database_name = "hotwheels-collection"
database_id = "d3fee45a-de0a-4f76-8d03-f461910f2bae"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "hotwheels-images"
custom_domain = "images.clausen.app"

[vars]
ENVIRONMENT = "production"
API_URL = "https://hotwheels.clausen.app"
R2_PUBLIC_URL = "https://images.clausen.app"

[build]
command = "npm install && npm run build"
output_dir = "dist"

[site]
bucket = "./dist"

[dev]
port = 8788