name = "hotwheels-collection"
compatibility_date = "2024-02-20"

[[d1_databases]]
binding = "DB"
database_name = "hotwheels-collection"
database_id = "47ebe64b-d99a-46b9-8ed1-680df6367403"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "hotwheels-images"
custom_domain = "images.clausen.app"

[vars]
ENVIRONMENT = "production"
API_URL = "https://hotwheels.clausen.app"
R2_PUBLIC_URL = "https://images.clausen.app"

[site]
bucket = "./dist"

[build]
command = "npm install && npm run build"
output_dir = "dist"

# Pages configuration
pages_build_output_dir = "dist"

[dev]
port = 8788