name = "authworker"  # This should match your worker name in Cloudflare
main = "src/auth.ts"
compatibility_date = "2024-02-14"

[[d1_databases]]
binding = "DB"
database_name = "hotwheels-auth"
database_id = "2f1e9091-6e84-4601-a63b-396c41adcc44"

[vars]
ENVIRONMENT = "production"

# Routes
[[routes]]
pattern = "access.clausen.app"
custom_domain = true
